### ISSUE TITLE
Optionally, IDFA should be used as the initial anonymous identity

### ISSUE THREAD

**Issue by billinghamj** [gosquared/gosquared-ios#10]
IDFA is often used to track attribution from advertising campaigns to conversions - e.g. Facebook ads to native app installation. There is no other feasible way of tracking conversion on iOS due to the security & privacy features on the platform.

It'd be good if the GoSquared SDK defaulted to the IDFA as the user's initial anonymous identity. After calling `unidentify` however, the IDFA probably should not be used, as the identity needs to be different.

Very important that this doesn't happen without it explicitly being enabled by the app (Apple will reject apps which do not declare use of IDFA).

Additionally, the user's "Limit Ad Tracking" preference might need to be checked - though I'm not sure if it applies to this use-case or not.

**Comment by edwellbrook** [comment]
Hey James! Thanks for taking the time to open this issue.

I'd love to know more about how you then go about using the IDFA. Specifically how do you then link up that a person has come from Facebook etc.?

I'm hesitant to add in IDFA directly since as you say Apple may reject apps if people do not realise they have to declare this. I'd be much more interested in hearing how you go about using that information and seeing if we can help make that process easier for you.

Thanks!

**Comment by billinghamj** [comment]
See these docs: https://developer.apple.com/library/ios/documentation/AdSupport/Reference/ASIdentifierManager_Ref/

The `advertisingIdentifier` (more commonly referred to as IDFA - ID For Advertising) is the same between apps on the same device. So if my app, and Facebook both request the IDFA, we'll both get the same value. This makes it possible to track conversions, because there is no other way of getting a consistent-between-apps identifier.

I'd strongly recommend supporting IDFA natively - as it is used incredibly widely. There are a lot of different ways of handling opt-in/out though:

- checking whether `AdSupport` is linked - [Mixpanel](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L908-L909) [Facebook](https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/Internal/AppEvents/FBSDKAppEventsUtility.m#L93-L94) [MoPub](https://github.com/mopub/mopub-ios-sdk/blob/master/MoPubSDK/Internal/Utility/MPIdentityProvider.m#L30) [Segment](https://github.com/segmentio/analytics-ios/blob/59d69a44c42d09fb5625d72a4a54afb366116f50/Pod/Classes/Internal/SEGAnalyticsUtils.m#L172-L173) [Quantcast](https://github.com/quantcast/ios-measurement/blob/master/Quantcast-iOS-Measurement/QuantcastUtils.m#L587-L589)
- checking for a build flag - [Mixpanel](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L907)
- making a separate CocoaPod - [Google](https://cocoapods.org/pods/GoogleIDFASupport)
- providing another subspec - [Google planning](https://code.google.com/p/analytics-issues/issues/detail?id=706)

While there doesn't seem to be a "correct" way, most SDKs seem to have gone with the option automatically using it if it is available (i.e. if the app developer has linked AdSupport.framework), with an opt out flag. My opinion is that it's probably best to go with the crowd and conform to the apparent standard.

Also important to note regarding app store review: https://github.com/mixpanel/mixpanel-iphone/issues/109#issuecomment-34096176 - this is because Apple does a little bit of static analysis on app binaries to check for private/conditional API usage

**Comment by steve228uk** [comment]
If IDFA is completely optional then I'm cool with it. My concern is the way it's checked. We include AdSupport as it's required by the GoogleCast SDK but we don't use the IDFA or touch any of the methods included (though this is probably something Google should be fixing).

**Comment by billinghamj** [comment]
@steve228uk It would be entirely optional. The rules & requirements around using it are very strict, so using it without explicit opt-in would be a huge mistake.

**Comment by edwellbrook** [comment]
Closing this issue because:

- we currently don't have a way of showing or using the anonymous id, it's only an internal id. realistically this should be called something like session id, which is more appropriate for how it's used
- you can set the IDFA as a property against a person's People profile should you need it. not ideal and doesn't cover every use case, but good enough for the majority of them

If this reasoning isn't sensible and you still want this looked into, please leave a comment. Thanks!
