### ISSUE TITLE
Consider tvOS Support

### ISSUE THREAD

**Issue by steve228uk** [gosquared/gosquared-ios#5]
The framework currently works perfectly with tvOS but will need changes to the Podspec in order to install. The only problem with multiple targets is that subspecs don't work with them so an alternative would need to be considered.

Happy to submit a PR for this, would just need to figure out a workaround for the subspecs. Best solution would probably be to add a `autotrackingEnabled` variable to the `sharedTracker` to enable/disable the categories/extensions.

**Comment by edwellbrook** [comment]
Hey Steve! Would love it if you submitted a PR :smile: 

Just having a look around because I hadn't heard of the multiple targets and subspecs issue before. Found this, which seems to do a similar thing to us in their podspec, which supports tvOS: https://github.com/Moya/Moya/blob/1d13c8bf1fbb081f73003c1d37526524f851ff36/Moya.podspec

I've not played around with any of the tvOS stuff yet so bare with me on all this :sweat: 

How're you thinking the `autotrackingEnabled` would work at a code level? Personally, I want to make opting in and out of auto tracking as easy as possible, and not mess around too much if people are opting out (I don't really want to be swizzling unless we're definitely going to be tracking that view). Thoughts?

**Comment by steve228uk** [comment]
@edwellbrook Ooh, I might be mistaking about the subspecs then. Will have another test and see if we can get that working. If it does I'll submit a PR tonight.

Might also be worth looking into enabling/disabling of the auto-swizzling even if autoload has been included anyway and may allow for simplification in terms of the subspecs.
